# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/export_nb',
                'doc_host': 'https://radekosmulski.github.io',
                'git_url': 'https://github.com/radekosmulski/export_nb',
                'lib_path': 'export_nb'},
  'syms': { 'export_nb.core': { 'export_nb.core.export_nb': ('core.html#export_nb', 'export_nb/core.py'),
                                'export_nb.core.strip_directives': ('core.html#strip_directives', 'export_nb/core.py'),
                                'export_nb.core.write_cells': ('core.html#write_cells', 'export_nb/core.py')}}}
